Repository WebSorcery/testcase-generator, pull requests merged in 2023-12, with the labels that each got.

#28 made ui changes
  components/style/index.js
  pages/footer.js
  pages/index.js
  styles/Home.module.css
  styles/globals.css
Labels: missing-jira, 5 min review

#31 Oauth using Clerk
  middleware.js
  package.json
  pages/_app.js
  pages/index.js
  pages/sign-in/[[...index]].jsx
  pages/sign-up/[[...index]].jsx
  styles/Home.module.css
Labels: missing-jira, 5 min review

#37 Email function embedded
  .gitignore
  components/generator/array/arrayGeneratorFunc.js
  components/generator/graph/graphGeneratorFunc.js
  components/generator/integer/integerGeneratorFunc.js
  components/generator/linkedList/linkedListGeneratorFunc.js
  components/generator/palindrome/palindromeGeneratorFunc.js
  components/generator/string/stringGeneratorFunc.js
  config/nodemailer.js
  lib/api.js
  package.json
  pages/api/confirm.js
Labels: missing-jira, 10 min review

#38 Corrected all errors
  components/generator/palindrome/palindromeGeneratorFunc.js
  components/generator/string/stringGeneratorFunc.js
  lib/api.js
  pages/api/confirm.js
Labels: missing-jira, 1 min review

#40 fix email issue
  .github/workflows/action.yml
  .github/workflows/take_issue.yml
  components/generator/array/arrayGenerator.js
  components/generator/array/arrayGeneratorFunc.js
  components/generator/integer/integerGenerator.js
  components/generator/linkedList/linkedListGenerator.js
  components/generator/palindrome/palindromeGenerator.js
  components/generator/string/stringGenerator.js
  config/nodemailer.js
  lib/api.js
  pages/api/confirm.js
  pages/index.js
  pages/sign-in/[[...index]].jsx
  pages/sign-up/[[...index]].jsx
Labels: missing-jira, 5 min review

#42 Made the website more interactive
  components/generator/array/arrayGenerator.js
  components/generator/binaryTreeGenerator.js
  components/generator/graph/graphGenerator.js
  components/generator/integer/integerGenerator.js
  components/generator/linkedList/linkedListGenerator.js
  components/generator/matrixGenerator.js
  components/generator/palindrome/palindromeGenerator.js
  components/generator/string/stringGenerator.js
  components/style/index.js
  pages/about.js
  pages/contact.js
  pages/footer.js
  pages/index.js
  pages/nav.js
  styles/Home.module.css
Labels: 30 min review, missing-jira
